### ISSUE TITLE
SSR Error

### ISSUE THREAD

**Issue by rjsandman** [cloudinary/cloudinary-svelte#2]
Hello,

I'm getting this error:

<Image> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

**Comment by patrick-tolosa** [comment]
Hello @sandman18,
We're investigating this issue and will provide more information when it's available.

If you can provide any additional information or a reproduction repo that would be great.

**Comment by Miguel-Bento-Github** [comment]
Similar here. Every time I update something the error appears.

Current dependencies 
```

 "dependencies": {
    "compression": "^1.7.1",
    "polka": "next",
    "sirv": "^0.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@cloudinary/svelte": "0.0.1-alpha.1",
    "@rollup/plugin-babel": "^5.0.0",
    "@rollup/plugin-commonjs": "^12.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "@rollup/plugin-replace": "^2.2.0",
    "autoprefixer": "^9.8.5",
    "npm-run-all": "^4.1.5",
    "postcss": "^7.0.32",
    "rollup": "^2.3.4",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^5.3.0",
    "sapper": "^0.27.0",
    "sass": "^1.26.10",
    "svelte": "^3.0.0",
    "svelte-preprocess": "^4.0.8"
  }
```

rollup config
```

import resolve from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import commonjs from '@rollup/plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import babel from '@rollup/plugin-babel';
import { terser } from 'rollup-plugin-terser';
import config from 'sapper/config/rollup.js';
import pkg from './package.json';
import sveltePreprocess from 'svelte-preprocess';

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) =>
  (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning);

const preprocess = sveltePreprocess({
  scss: {
    prependData: `@import 'src/style/keyframes.scss'; @import 'src/style/variables.scss'; `,
  },
  postcss: {
    plugins: [require('autoprefixer')],
  },
});

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),

    plugins: [
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        dev,
        hydratable: true,
        preprocess,
        emitCss: true,
      }),
      resolve({
        browser: true,
        dedupe: ['svelte'],
      }),
      commonjs(),

      legacy &&
        babel({
          extensions: ['.js', '.mjs', '.html', '.svelte'],
          babelHelpers: 'runtime',
          exclude: ['node_modules/@babel/**'],
          presets: [
            [
              '@babel/preset-env',
              {
                targets: '> 0.25%, not dead',
              },
            ],
          ],
          plugins: [
            '@babel/plugin-syntax-dynamic-import',
            [
              '@babel/plugin-transform-runtime',
              {
                useESModules: true,
              },
            ],
          ],
        }),

      !dev &&
        terser({
          module: true,
        }),
    ],

    preserveEntrySignatures: false,
    onwarn,
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    plugins: [
      replace({
        'process.browser': false,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        generate: 'ssr',
        preprocess,
        dev,
      }),
      resolve({
        dedupe: ['svelte'],
      }),
      commonjs(),
    ],
    external: Object.keys(pkg.dependencies).concat(
      require('module').builtinModules || Object.keys(process.binding('natives')),
    ),

    preserveEntrySignatures: 'strict',
    onwarn,
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    plugins: [
      resolve(),
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      commonjs(),
      !dev && terser(),
    ],

    preserveEntrySignatures: false,
    onwarn,
  },
};

```

Cheers

**Comment by idobarnoam** [comment]
Hi @Miguel-Bento-Github The Svelte SDK is currently in Alpha and is not fit for production yet.

We are taking this issue into account and we would look into it. It would be handled in later, in more ready versions.

**Comment by Miguel-Bento-Github** [comment]
> Hi @Miguel-Bento-Github The Svelte SDK is currently in Alpha and is not fit for production yet.
> 
> We are taking this issue into account and we would look into it. It would be handled in later, in more ready versions.

No worries. I just raised it so that you could take a look. Having some dependency and config logs will surely help.
Thanks for the good work!

**Comment by danielstopp** [comment]
Are there any news to this issue? I'm still having this problem and I don't quite know how to solve it, apart from using the library with plain Svelte. I'm thankful for any tips or tricks.

**Comment by roeeba** [comment]
Hi @Odiumediae, we still don't have an ETA for the fix. We will update here once there'll be any progress. 
Thank you for your patience.

**Comment by cupcakearmy** [comment]
Same here :)

**Comment by cupcakearmy** [comment]
For the time being this works

```
<script>
  import { Cloudinary } from 'cloudinary-core'
  import { onMount } from 'svelte'

  export let src = ''
  export let options = {
    fetchFormat: 'auto',
    quality: 'auto',
  }
  export let alt = ''

  let img
  let attrs = {}

  onMount(() => {
    const cl = Cloudinary.new({ cloud_name: 'myaccount' })
    attrs = cl.imageTag(src, options ).attributes()
  })
</script>

<img bind:this={img} {...$$restProps} {alt} {...attrs} />
```

**Comment by cupcakearmy** [comment]
@roeeba I've written a fully working package. If you need any inspiration for the official one (with lazy loading and automatic dynamic image sizes)
https://github.com/cupcakearmy/svelte-cloudinary

**Comment by ghost** [comment]
Hi @cupcakearmy, really great work! 
Would you like to contribute a fix for SSR or other enhancements to this sdk?

**Comment by cupcakearmy** [comment]
Thanks :)
@maoznir sure. The SSR fix is quite simple I believe. I though you were already working on it otherwise I'd already done a PR :)
For the other enhancements: in theory yes, although I took a bit of a different approach (svelte [actions](https://svelte.dev/docs#use_action) as opposed to a dedicated component) for reasons listed [here](https://github.com/cupcakearmy/svelte-cloudinary#-why-an-action-and-not-component), so I don't know how well they fit in a component :)
Maybe I can see if I get the lazy loading in there.

**Comment by cupcakearmy** [comment]
@maoznir and of course whenever the official solution is finished I'd be happy to deprecate my package and point it here. The official "sdk" should always be the way to go 👍

**Comment by ghost** [comment]
@cupcakearmy thats awesome! wanna start with the SSR fix?

**Comment by cupcakearmy** [comment]
@maoznir I've looked at the code. Actually it seems as it is already SSR Compatible. you just imported it wrongly.

```
{
  "name": "@cloudinary/svelte",
  "svelte": "src/index.js",    <- This has to point to the source code, otherwise sapper cannot compile.
  "module": "dist/cloudinary-svelte.mjs",
  "main": "dist/cloudinary-svelte.js",

  "files": ["dist", "src"]       <- Also inlcude src
}

Due to a [recent bug](https://github.com/sveltejs/rollup-plugin-svelte/pull/151) I needed to upgrade `rollup-plugin-svelte` to `6.1.1`

```

I could do a PR, but it's litteraly 2 lines of config file, so I think I will leave it up to you guys :)

**Comment by jdmedlock** [comment]
Hi. Are there any updates on this issue? Thanks in advance.

**Comment by ghost** [comment]
Hi @jdmedlock this has been fixed in 0.0.1-alpha.2, please let us know if it works for you, thanks!

**Comment by jdmedlock** [comment]
Thank you and the team for your help @maoznir. It did correct the issue I was experiencing. 

I do notice that after this change I'm getting the following warning when I start my site though. It's not a show stopper, but something you should be aware of.
```
> run-p watch:*


> chs73@0.0.1 watch:dev
> sapper dev


> chs73@0.0.1 watch:css
> postcss src/assets/global.pcss -o static/global.css -w

✔ server (14.6s)
• client
node_modules/@cloudinary/svelte/src/Video.svelte
A11y: Media elements must have a <track kind="captions">
 8: </script>
 9: 
10: <video {...videoTag.attributes()}>
    ^
11:   {@html videoTag.content()}
12: </video>
✔ service worker (34ms)
> Listening on http://localhost:3000
```

**Comment by ghost** [comment]
@jdmedlock happy to hear and thanks for the update!
The warning you're getting is coming from svelte, it can be disabled. see here: https://github.com/sveltejs/svelte/issues/5967

**Comment by flbn** [comment]
can we mark this as closed or are people still experiencing these SSR issues? sorta confusing for someone about to start a new project using cloudinary and kit.

**Comment by ghost** [comment]
@flbn thanks for the ping, closing this as it was fixed.
